package com.creedpetitt.workersdk;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WorkflowClient {

    private final String orchestratorUrl;
    private final HttpClient httpClient;
    private static final ObjectMapper MAPPER = new ObjectMapper();

    public WorkflowClient(String orchestratorUrl) {
        // Ensure url doesn't end with a slash for clean concatenation
        this.orchestratorUrl = orchestratorUrl.endsWith("/") ?
                orchestratorUrl.substring(0, orchestratorUrl.length() - 1) : orchestratorUrl;
        this.httpClient = HttpClient.newHttpClient();
    }

    /**
     * Defines a new workflow in the Orchestrator.
     * @param workflowId The unique identifier for the workflow.
     * @param steps An ordered list of action strings.
     * @throws Exception If the HTTP request fails.
     */
    public void defineWorkflow(String workflowId, List<String> steps) throws Exception {
        Map<String, Object> payload = new HashMap<>();
        payload.put("id", workflowId);

        List<Map<String, Object>> stepObjects = new ArrayList<>();
        for (int i = 0; i < steps.size(); i++) {
            Map<String, Object> step = new HashMap<>();
            step.put("stepIndex", i);
            step.put("action", steps.get(i));
            stepObjects.add(step);
        }
        payload.put("steps", stepObjects);

        String json = MAPPER.writeValueAsString(payload);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(orchestratorUrl + "/workflow"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(json))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 201 && response.statusCode() != 200) {
            throw new RuntimeException("Failed to define workflow. Status: " + response.statusCode() + " Body: " + response.body());
        }
    }

    /**
     * Triggers a run of a defined workflow.
     * @param workflowId The ID of the workflow to run.
     * @param input The input string for the first step.
     * @return The unique runId generated by the orchestrator.
     * @throws Exception If the HTTP request fails.
     */
    public String triggerWorkflow(String workflowId, String input) throws Exception {
        return triggerWorkflow(workflowId, input, null);
    }

    /**
     * Triggers a run of a defined workflow with an idempotency key.
     * @param workflowId The ID of the workflow to run.
     * @param input The input string for the first step.
     * @param idempotencyKey An optional key to prevent duplicate runs.
     * @return The unique runId generated by the orchestrator.
     * @throws Exception If the HTTP request fails.
     */
    public String triggerWorkflow(String workflowId, String input, String idempotencyKey) throws Exception {
        Map<String, String> payload = new HashMap<>();
        payload.put("input", input);

        String json = MAPPER.writeValueAsString(payload);

        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()
                .uri(URI.create(orchestratorUrl + "/workflow/" + workflowId + "/trigger"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(json));

        if (idempotencyKey != null && !idempotencyKey.isEmpty()) {
            requestBuilder.header("Idempotency-Key", idempotencyKey);
        }

        HttpRequest request = requestBuilder.build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Failed to trigger workflow. Status: " + response.statusCode() + " Body: " + response.body());
        }

        return response.body();
    }

    /**
     * Retrieves the status and history of a specific workflow run.
     * @param runId The unique identifier of the run.
     * @return A JSON string containing the run status and step results.
     * @throws Exception If the HTTP request fails.
     */
    public String getRunStatus(String runId) throws Exception {
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(orchestratorUrl + "/workflow/run/" + runId))
                .header("Accept", "application/json")
                .GET()
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Failed to get run status. Status: " + response.statusCode() + " Body: " + response.body());
        }

        return response.body();
    }
}
