import urllib.request
import urllib.error
import json
from typing import List, Optional, Dict, Any

class WorkflowClient:
    def __init__(self, orchestrator_url: str):
        # Ensure no trailing slash
        self.orchestrator_url = orchestrator_url.rstrip('/')

    def define_workflow(self, workflow_id: str, steps: List[str]) -> None:
        """
        Defines a new workflow in the Orchestrator.
        """
        payload = {
            "id": workflow_id,
            "steps": [{"action": action, "stepIndex": i} for i, action in enumerate(steps)]
        }
        
        self._make_request("/workflow", payload=payload, method="POST")

    def trigger_workflow(self, workflow_id: str, input_data: str, idempotency_key: Optional[str] = None) -> str:
        """
        Triggers a run of a defined workflow.
        Returns the unique runId generated by the orchestrator.
        """
        payload = {"input": input_data}
        headers = {}
        
        if idempotency_key:
            headers['Idempotency-Key'] = idempotency_key

        return self._make_request(f"/workflow/{workflow_id}/trigger", payload=payload, headers=headers, method="POST")

    def get_run_status(self, run_id: str) -> Dict[str, Any]:
        """
        Retrieves the status and history of a specific workflow run.
        """
        response_str = self._make_request(f"/workflow/run/{run_id}", method="GET")
        return json.loads(response_str)

    def _make_request(self, path: str, payload: dict = None, headers: dict = None, method: str = "GET") -> str:
        url = f"{self.orchestrator_url}{path}"
        
        req_headers = {}
        json_data = None
        
        if payload is not None:
            json_data = json.dumps(payload).encode('utf-8')
            req_headers['Content-Type'] = 'application/json'
            
        if headers:
            req_headers.update(headers)

        req = urllib.request.Request(url, data=json_data, headers=req_headers, method=method)
        
        try:
            with urllib.request.urlopen(req) as response:
                return response.read().decode('utf-8')
        except urllib.error.HTTPError as e:
            error_body = e.read().decode('utf-8')
            raise Exception(f"Request failed. Status: {e.code}, Body: {error_body}")
        except urllib.error.URLError as e:
             raise Exception(f"Failed to connect to Orchestrator: {e.reason}")