export class WorkflowClient {
    private orchestratorUrl: string;

    constructor(orchestratorUrl: string) {
        // Ensure no trailing slash
        this.orchestratorUrl = orchestratorUrl.endsWith('/') 
            ? orchestratorUrl.slice(0, -1) 
            : orchestratorUrl;
    }

    /**
     * Defines a new workflow in the Orchestrator.
     * @param workflowId The unique identifier for the workflow.
     * @param steps An ordered array of action strings.
     */
    async defineWorkflow(workflowId: string, steps: string[]): Promise<void> {
        const payload = {
            id: workflowId,
            steps: steps.map((action, index) => ({
                action: action,
                stepIndex: index
            }))
        };

        const response = await fetch(`${this.orchestratorUrl}/workflow`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        
        if (!response.ok) {
            const body = await response.text();
            throw new Error(`Failed to define workflow. Status: ${response.status}, Body: ${body}`);
        }
    }

    /**
     * Triggers a run of a defined workflow.
     * @param workflowId The ID of the workflow to run.
     * @param input The input string for the first step.
     * @param idempotencyKey An optional key to prevent duplicate runs.
     * @returns The unique runId generated by the orchestrator.
     */
    async triggerWorkflow(workflowId: string, input: string, idempotencyKey?: string): Promise<string> {
        const payload = { input: input };
        const headers: Record<string, string> = {
            'Content-Type': 'application/json'
        };
        
        if (idempotencyKey) {
            headers['Idempotency-Key'] = idempotencyKey;
        }

        const response = await fetch(`${this.orchestratorUrl}/workflow/${workflowId}/trigger`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(payload)
        });

        const body = await response.text();

        if (!response.ok) {
            throw new Error(`Failed to trigger workflow. Status: ${response.status}, Body: ${body}`);
        }

        return body;
    }

    /**
     * Retrieves the status and history of a specific workflow run.
     * @param runId The unique identifier of the run.
     * @returns A JSON object containing the run status and step results.
     */
    async getRunStatus(runId: string): Promise<any> {
        const response = await fetch(`${this.orchestratorUrl}/workflow/run/${runId}`, {
            method: 'GET',
            headers: { 'Accept': 'application/json' }
        });

        if (!response.ok) {
            const body = await response.text();
            throw new Error(`Failed to get run status. Status: ${response.status}, Body: ${body}`);
        }

        return await response.json();
    }
}
